@TodoApi_HostAddress = https://localhost:7096



POST {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json

{
    "name":"walk dog",
    "isComplete":true
}

###

GET {{TodoApi_HostAddress}}/todoitems

###

@id=0
GET {{TodoApi_HostAddress}}/todoitems/1

###

POST {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json

{
  //Todo
}

###

PUT {{TodoApi_HostAddress}}/todoitems/{{id}}
Content-Type: application/json

{
  //Todo
}

###

PUT {{TodoApi_HostAddress}}/todoitems/1
Content-Type: application/json

  {
    "id": 1,
    "name": "feed fish",
    "isComplete": false
  }

###

POST {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json

{
  "name": "walk dog",
  "isComplete": true
}


###

PATCH {{TodoApi_HostAddress}}/todoitems/1
Content-Type: application/json

{
  "name": "run errands"
}

###

DELETE {{TodoApi_HostAddress}}/todoitems/1

###
